apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-note-app
  labels:
    app: my-note-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-note-app
  template:
    metadata:
      labels:
        app: my-note-app
    spec:
      containers:
        - name: my-note-app
          image: your-dockerhub-username/my-note-app:latest   # Jenkins will replace this
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "django_notes_app.settings"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: my-note-app-service
spec:
  selector:
    app: my-note-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer


