apiVersion: apps/v1
kind: Deployment
metadata:
  name: notesapp-deployment
  labels:
    app: notesapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notesapp
  template:
    metadata:
      labels:
        app: notesapp
    spec:
      containers:
        - name: notesapp
          image: sunainaraj/my-note-app:1.2   # <-- updated version
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: notesapp.settings
          imagePullPolicy: Always

